DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS nasa;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE nasa (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url_apod TEXT,
  title TEXT,
  year_apod INTEGER,
  month_apod INTEGER,
  day_apod INTEGER, 
  explanation TEXT,
  copyright TEXT,
  hdurl TEXT,
  media_type TEXT
);